name: Documentation Updates

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  build-html:
    name: Validate & Build HTML
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: docker://cilium/docs-builder:latest
        with:
          entrypoint: ./Documentation/check-build.sh
          args: html
