name: Nightly
on:
  pull_request: {}
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
jobs:
  policy-stress-test:
    name: Start Nightly Policy Stress tests
    runs-on: ubuntu-18.04
    steps:
      - name: Trim git sha
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${GITHUB_SHA:0:9})"
      - name: Request GKE test cluster
        uses: docker://quay.io/isovalent/gke-test-cluster-requester:fe34abda190c31680968ba62634c788428d91706
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --debug --namespace=test-clusters --image=cilium/cilium-test-dev:7d5b911e6 "/usr/local/bin/cilium-test-gke.sh" "quay.io/cilium/cilium:latest" "quay.io/cilium/operator-generic:latest" "quay.io/cilium/hubble-relay:latest" "NightlyPolicyStress"
